### ISSUE TITLE
main_resource is incorrect when using get_subsites

### ISSUE THREAD

**Issue by jtweeder** [O365/python-o365#214] opened 2019-03-25 21:13 UTC
I have not been able to trace back where this is exactly happening to propose a solution, but here is the behavior.

First I created a sharepoint site.

```python
site = acct.sharepoint().get_site('root','/path/to_site')
```

This site conatins three subsites, and wanting to create a site instance from the first listed.
```python
sub_site = site.get_subsites()[0]
```

It seems to build the the site for the sub_site without issue until I try to interact with the API where I get a 400, Bad Request Resource not found.  Looking at the error it appeared that the url for the subsite was stacked  on top of the site information.  

Example Error:
```400 Client Error: Bad Request for url: https://graph.microsoft.com/v1.0/sites/<sharepointaddress>,<siteID>/sites/<sharepointaddress>,<subsiteID>```

Looking at the .main_resource of each of the objects I can see the repetition in the subsite.

```python
sub_site.main_resource
'sites/<sharepointaddress>,<SiteID>sites/<sharepointaddress>,<subsiteID>'
```

while the site.main_resource is as follows:
```'sites/<sharepointaddress>,<SiteID>'```

If I make a site object with a path directly to the site I want from the subsites it works, but then I cant use the listing of subsites to my advantage.

```sub_site =  acct.sharepoint().get_site('root','/path/to_site/subsite')```

Now the sub_site works as expected and has the following under sub_site.main_resource:
```'sites/<SharepointAddress>,<subsiteID>'```

I hope that explanation is clear enough for what I was experiencing, and feel free to ask any clarifying questions.

**Comment by janscas** [comment] 2019-03-28 10:15
I'm not using the sharepoint functionality right now so I can not test it.

But I'm sure that the problem is here:

https://github.com/O365/python-o365/blob/master/O365/sharepoint.py#L277

This line works as intended when you get a site by from the Sharepoint class.
But not when getting the list of subsites from a site.

This should be checked instead:
 -  is the parent a site `isinstance(parent, Site)`? then set the resource as a new site (don't stack site resources)
- is the parent another class? then work as it is doing now.

This is a pretty easy fix. If you want to get your hands dirty on this tell me. If not I'll correct it the near future.

**Comment by jtweeder** [comment] 2019-03-28 14:02
My pleasure.  The foundation of the package is very straightforward and easy to build upon. 

With your troubleshooting information I think I can fix this now.  I will take a look at this fix to help free up your time, and it should be easier since I am using the sharepoint piece daily. 

 I am hopeful to do submit some documentation on the sharepoint usage as well since it is fairly easy for me to copy and paste some code into some docs.

**Closed** 2019-03-28 19:46 UTC
Labels: bug
