### ISSUE TITLE
Incompatible tzlocal version causing AttributeError

### ISSUE THREAD

**Issue by ottoaho** [O365/python-o365#670] opened 2021-08-16 10:32 UTC
Upon setting message category, my application started throwing error:
`AttributeError: 'zoneinfo.ZoneInfo' object has no attribute 'localize'`

I tracked this down to the dependency `tzlocal`.
- O365 accepts `tzlocal>=1.5.0`
- `tzlocal==3.0` was released on 2018-08-13.
- When explicitly installing `tzlocal==2.1`, everything works as usual.

**Comment by mw-deb** [comment] 2021-08-17 07:49
Could be a duplicate of issue #591.

**Comment by janscas** [comment] 2021-09-03 10:04
Ok, that's the issue as tzlocal 3.0 uses now ZoneInfo objects:

> With version 3.0 of tzlocal, it no longer returns pytz objects, but zoneinfo objects. This, and the dropping of Python 2 support, are the only differences, so if you need to use pytz objects, you can continue to use tzlocal 2.1.


I'll pin tzlocal to 2.1 in the requirements so this will be fixed.

**Closed** 2021-09-03 10:43 UTC
