### ISSUE TITLE
TypeError: 'OAuth2Session' object is not callable in Connection.oauth2

### ISSUE THREAD

**Issue by luizcieslak** [O365/python-o365#125] opened 2018-09-24 13:43 UTC
Hi, 

I'm trying to make an connection through OAuth2 using [these steps](https://github.com/O365/python-o365#connection). I set the response URL, authenticated it and paste it back in the input.

This is the script I'm trying to run:
```python
from O365 import Message, Attachment, Connection
c = Connection.oauth2(client_id, client_secret, store_token=True)

m = Message(auth=c.oauth)
m.setRecipients(receivers)
m.setSubject('I made an email script.')
m.setBody('Talk to the computer, cause the human does not want to hear it any more.')
m.sendMessage()
```

Now, when I run the script, I get this error:
```python
  File "C:/Users/luiz.cieslak/Documents/projeto-csc/MonitoriaPy/office.py", line 15, in <module>
    m.sendMessage()

  File "C:\Users\luiz.cieslak\AppData\Local\Continuum\anaconda3\lib\site-packages\O365\message.py", line 114, in sendMessage
    self.send_url, data, headers=headers, auth=self.auth,verify=self.verify)

  File "C:\Users\luiz.cieslak\AppData\Local\Continuum\anaconda3\lib\site-packages\requests\api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)

  File "C:\Users\luiz.cieslak\AppData\Local\Continuum\anaconda3\lib\site-packages\requests\api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)

  File "C:\Users\luiz.cieslak\AppData\Local\Continuum\anaconda3\lib\site-packages\requests\sessions.py", line 494, in request
    prep = self.prepare_request(req)

  File "C:\Users\luiz.cieslak\AppData\Local\Continuum\anaconda3\lib\site-packages\requests\sessions.py", line 437, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),

  File "C:\Users\luiz.cieslak\AppData\Local\Continuum\anaconda3\lib\site-packages\requests\models.py", line 309, in prepare
    self.prepare_auth(auth, url)

  File "C:\Users\luiz.cieslak\AppData\Local\Continuum\anaconda3\lib\site-packages\requests\models.py", line 540, in prepare_auth
    r = auth(self)

TypeError: 'OAuth2Session' object is not callable
```
Did I miss something?

**Comment by luizcieslak** [comment] 2018-09-24 17:15
Oops, I realized that the version 0.9.15 installed by pip is not the same updated in this repo. So, I did a local copy the `Message` class from `fluent_message.py` and it worked with `oauth` argument.

Please let me know when you launch a updated version to PyPi.

**Comment by roycem90** [comment] 2018-09-25 22:31
@Narcolapser can we somehow automate the packaging based on tags?

**Comment by Narcolapser** [comment] 2018-09-27 14:39
I will look into it.

**Comment by Narcolapser** [comment] 2018-10-11 13:38
What's the specific error you are getting? And what's your code?

**Comment by vicosurge** [comment] 2018-10-11 22:01
Same error as described initially in this thread with the same code, I was following the documentation provided in the code section but I kept getting an error not being in '__init__' so I tried what was shown here, reading through the comments I had assumed that I should not be getting this message anymore? Maybe I got it all mixed up.

**Comment by Narcolapser** [comment] 2018-10-18 15:39
Can you post your code? This will allow me to see if the problem is specific to you or if you found a error in general.

**Comment by janscas** [comment] 2019-01-09 12:54
Closing this the user didn't answer and It is referring to the old api.

**Closed by janscas** 2019-01-09 12:54 UTC
Labels: help wanted
