### ISSUE TITLE
failed to send mail issue

### ISSUE THREAD

**Issue by plutoid** [O365/python-o365#292] opened 2019-08-22 04:55 UTC
hi,

does anyone succeed to send the mail? I can be sure the graph api permissions have been enabled, but below sample code no luck.

versions:
python3.4
O365 2.0.1
```
from O365 import Account
from O365 import MSGraphProtocol

my_protocol = MSGraphProtocol(api_version='v2.0')
credentials = ("app client", "app secrect")
emailAcc = Account(credentials=credentials,protocol=my_protocol)

if not emailAcc.is_authenticated:
    emailAcc.authenticate(scopes= ['https://graph.microsoft.com/Mail.Send'])

m = emailAcc.new_message()

m.to.add('test@test.com')
m.subject = 'from O365 auto email!'
m.body = 'Email Test'
m.send()
```

it always complains the error like below,after I past the authentication url:
```
Unable to fetch auth token. Error: (invalid_request) AADSTS90023: Public clients can't send a client secret.
Trace ID: 53b0d0ed-22ac-4093-a821-5c1ff6ee5c00
Correlation ID: 3c9d672a-3c62-45f7-8d37-e4dc73b3b085
Timestamp: 2019-08-22 04:45:16Z
Something go wrong. Please try again.
Traceback (most recent call last):
  File "o365mail.py", line 16, in <module>
    m.send()
  File "/usr/lib/python3.4/site-packages/O365/message.py", line 614, in send
    response = self.con.post(url, data=data)
  File "/usr/lib/python3.4/site-packages/O365/connection.py", line 665, in post
    return self.oauth_request(url, 'post', data=data, **kwargs)
  File "/usr/lib/python3.4/site-packages/O365/connection.py", line 641, in oauth_request
    self.session = self.get_session(load_token=True)
  File "/usr/lib/python3.4/site-packages/O365/connection.py", line 449, in get_session
    raise RuntimeError('No auth token found. Authentication Flow needed')
RuntimeError: No auth token found. Authentication Flow needed

```

thanks! any guys have an ideas for this?

Regards, Howard

**Comment by MaxWinterstein** [comment] 2019-08-22 10:12
first, i can confirm this is working for me right now, as i currently fiddle around with it.

regarding your error message i can only guess that you did not add a redirect url to your app registration, and therefore it became an public client (see https://stackoverflow.com/questions/38786249/).

```python
from O365 import Account
from O365 import MSOffice365Protocol

my_protocol = MSOffice365Protocol(api_version='v2.0')
credentials = ('XXX', 'XXX')
emailAcc = Account(credentials=credentials, protocol=my_protocol, tenant_id="XXXX")

if not emailAcc.is_authenticated:
    emailAcc.authenticate(scopes=['basic', 'Mail.Send'], tenant_id="")

m = emailAcc.new_message()

m.to.add('winterstein@m2p.net')
m.subject = 'Testing auto email!'
m.body = 'Email Test'
m.send()
```

**Comment by janscas** [comment] 2019-08-29 11:09
> Public clients can't send a client secret.

Here is the reason. You have to set the redirect url as @MaxWinterstein already said.

**Comment by janscas** [comment] 2019-09-25 11:19
Closing this as there's no answer

**Closed by janscas** 2019-09-25 11:19 UTC
