### ISSUE TITLE
Calendar Event Pull - Date Value Out of Range

### ISSUE THREAD

**Issue by MintyFresh0** [O365/python-o365#158] opened 2018-12-19 19:33 UTC
Hello, I am experiencing issues with calendar queries. It seems I cannot get a query to pull events properly, with the error "date value out of range". Please note that I have tried a few date ranges, ones that are certainly real and exist within my Calendar. Below is my code.

```
def calEventPullJobs():
        ###Code here was removed for simplicity. Schedule and calendars load properly here.
	
	try:                   #make query
		queryVar = my_calendar.new_query('start').greater_equal(dt.datetime(2018, 8, 25))
		queryVar.chain('and').on_attribute('end').less(dt.datetime(2018, 12, 25))
		print("Loaded: Calendar Query - Success.")
	except Exception as e:
		print (str(e))
			
	try:                     #load events
		print ("DEBUG-queryVar: {}".format(queryVar))
		events = my_calendar.get_events(query = queryVar)
		print("Loaded: Events - Success.")
	except Exception as e:
		print (str(e))		
		
	for event in events: #iterate events
		print (event.subject)	
		if event.subject is None:
			print ("WARNING: There is a blank event in the Outlook calendar")
		else:
			jobEventList.append(event.subject)
	return jobEventList
```

Note: I have tried multiple variations of
 ```
queryVar=my_calendar.new_query('start').greater_equal(dt.datetime(2018, 8, 25))
queryVar.chain('and').on_attribute('end').less(dt.datetime(2018, 12, 25))
```
such as
```
queryVar=my_calendar.new_query('start').greater_equal(dt.datetime(2018, 8, 25))
queryVar.chain('and').on_attribute('end').less_equal(dt.datetime(2018, 12, 25))
```
and 
```
queryVar=my_calendar.new_query('start').greater_equal(dt.datetime(2018, 8, 25)).chain('and').on_attribute('end').less_equal(dt.datetime(2018, 12, 25))
```

Regardless, I yield the same result. OUTPUT:

> -Loaded: Schedule - Success.
> -Loaded: Calendar - Success.
> -Loaded: Calendar Query - Success.
> -DEBUG-queryVar: Filter: start/dateTime ge '2018-08-25T04:00:00+00:00' and end/dateTime lt '2018-12-25T05:00:00+00:00'
> -Order: None
> -Select: None
> -date value out of range
> -Traceback (most recent call last):
> -File "QTOverviewer_GUI_100.py", line 157, in loadLists
> -jobDateCalList = m.calEventPullJobs()
> -File "C:\path\removed\securityparanoia\python_o365_test\Overviewer_Beta\1.0.0\QTOverviewer_Main_100.py", line 344, in calEventPullJobs
> -for event in events: #iterate events
> -UnboundLocalError: local variable 'events' referenced before assignment

Reason it barfs at events is because it fails to load the event list with the query, and prints "date value out of range" when it tries.

Environment Notes:
- Windows 10 64 Bit
- Running through MSYS/MinGW shell
- Python 3.7
- O365 1.0.2
- Scopes are ['https://graph.microsoft.com/Mail.ReadWrite', 'https://graph.microsoft.com/Mail.Send', 'https://graph.microsoft.com/Calendars.ReadWrite', 'https://graph.microsoft.com/Contacts.ReadWrite', 'offline_access'] 
- Mail read write and send work properly

**Comment by janscas** [comment] 2018-12-20 10:43
I've just run this and it absolutely works for me:

```python
# ...
calendar = account.schedule().get_default_calendar()

q = calendar.new_query('start').greater_equal(dt.datetime(2018, 8, 25))
q.chain('and').on_attribute('end').less(dt.datetime(2018, 12, 25))

events = calendar.get_events(limit=10, query=q)

for event in events:
    print(event)
```
The above snippet returns 10 events for me.

The `date value out of range` message it's not something that this library returns as just as this.
Can you set `logging.basicConfig(level=logging.DEBUG)` on your script and then paste the whole result.

**PLEASE DELETE THE PRIVATE TOKEN INFO WHEN PASTING THE OUTPUT.**

**Comment by MintyFresh0** [comment] 2018-12-20 17:06
Hey Janscas, here is the full logging.basicConfig (debug mode) output:

```
Loaded: Calendar - Success.
Loaded: Calendar Query - Success.
DEBUG-queryVar: Filter: start/dateTime ge '2018-08-25T04:00:00+00:00' and end/dateTime lt '2018-12-25T05:00:00+00:00'
Order: None
Select: None
INFO:O365.connection:Requesting (GET) URL: https://graph.microsoft.com/beta/users/m.roy@mercuryfilmworks.com/calendars/AQMkADNjZjdkZjJhLTljMDYtNDQAMWUtODA0My0yZjkwZDk3ODUxNWYARgAAA-ycYdq22mJNqg2XXXOkdHwHAMH9v4slMY5BjwG8gEnLjocAAAIBBgAAAMH9v4slMY5BjwG8gEnLjocAAAIwUwAAAA==/events
INFO:O365.connection:Request parameters: {'params': {'$top': 10, '$filter': "start/dateTime ge '2018-08-25T04:00:00+00:00' and end/dateTime lt '2018-12-25T05:00:00+00:00'"}, 'headers': {'Prefer': 'outlook.timezone="UTC"'}, 'allow_redirects': True}
DEBUG:requests_oauthlib.oauth2_session:Invoking 0 protected resource request hooks.
DEBUG:requests_oauthlib.oauth2_session:Adding token {'token_type': 'Bearer', 'scope': ['profile', 'openid', 'email', 'https://graph.microsoft.com/Calendars.ReadWrite', 'https://graph.microsoft.com/Contacts.ReadWrite', 'https://graph.microsoft.com/Mail.ReadWrite', 'https://graph.microsoft.com/Mail.Send', 'https://graph.microsoft.com/User.Read'], 'expires_in': 3600, 'ext_expires_in': 3600, 'access_token': 'eyJ0eXAiOiJKV1QiLCJub25jZSI6IkFRQUJBQUFBQUFDNXVuYTBFVUZnVElGOEVsYXh0V2pUdXozeEVqUWlQZ2N2MklmV0NrbDIwOUpjeHNveUhTZzZMckw3TDh4WTNuUnZPVDdsOU10VGFFRXhaLVlkM21sM05tWHhLWnM4aFJ2cF9Pc3FmR0hVU1NBQSIsImFsZyI6IlJTMjU2IiwieDV0IjoibmJDd1cxMXczWGtCLXhVYVh3S1JTTGpNSEdRIiwia2lkIjoibmJDd1cxMXczWGtCLXhVYVh3S1JTTGpNSEdRIn0.eyJhdWQiOiJodHRwczovL2dyYXBoLm1pY3Jvc29mdC5jb20iLCJpc3MiOiJodHRwczovL3N0cy53aW5kb3dzLm5ldC9mOTNlZjA1MC03YjMyLTQzNGMtODcxNi03ZTFhZWIyMzliYzYvIiwiaWF0IjoxNTQ1MzIzNTUwLCJuYmYiOjE1NDUzMjM1NTAsImV4cCI6MTU0NTMyNzQ1MCwiYWNjdCI6MCwiYWNyIjoiMSIsImFpbyI6IjQyUmdZT0NZY0xaTVo2dGhrM0w1QWRkVUZuNnZGYXYvL1A0WXFPbFdjdEcrTHZFV3Z3Y0EiLCJhbXIiOlsicHdkIl0sImFwcF9kaXNwbGF5bmFtZSI6Ik15dGNoVGVzdFB5QXBwR3JhcGgyLjAiLCJhcHBpZCI6ImMwZjc1MTRmLWMyZjgtNDdlOS04YmRjLTcyMjcxOGVjZGNkYiIsImFwcGlkYWNyIjoiMSIsImZhbWlseV9uYW1lIjoiUm95IiwiZ2l2ZW5fbmFtZSI6Ik15dGNoZWxsIiwiaXBhZGRyIjoiMTkyLjQwLjIzMi4yMjYiLCJuYW1lIjoiTXl0Y2hlbGwgUm95Iiwib2lkIjoiNGYwMDBkMTEtMWRiMC00MWE0LWJlMTAtYzQ4YzFmMDEyZjI2Iiwib25wcmVtX3NpZCI6IlMtMS01LTIxLTIzMjU3OTczMDktNzQ0MDUyMDYxLTgxNTY1MDIyNC02OTU0IiwicGxhdGYiOiIzIiwicHVpZCI6IjEwMDM3RkZFQUM4MUFERTEiLCJzY3AiOiJDYWxlbmRhcnMuUmVhZFdyaXRlIENvbnRhY3RzLlJlYWRXcml0ZSBNYWlsLlJlYWRXcml0ZSBNYWlsLlNlbmQgVXNlci5SZWFkIHByb2ZpbGUgb3BlbmlkIGVtYWlsIiwic3ViIjoiLXNYaDA2b21nWWFPSE1fQUtRMk5KcElSc1RCUThpdS1icmp4R3Y3SDI1TSIsInRpZCI6ImY5M2VmMDUwLTdiMzItNDM0Yy04NzE2LTdlMWFlYjIzOWJjNiIsInVuaXF1ZV9uYW1lIjoibS5yb3lAbWVyY3VyeWZpbG13b3Jrcy5jb20iLCJ1cG4iOiJtLnJveUBtZXJjdXJ5ZmlsbXdvcmtzLmNvbSIsInV0aSI6IlZuREhvbUFWTjBLU09NU3hRWWM5QUEiLCJ2ZXIiOiIxLjAiLCJ4bXNfc3QiOnsic3ViIjoiNnMzaE53UXJXaEEzeGpVV1g2dDk0QnlQN3BhYWdYSzFmUWdiV09QWVlXUSJ9LCJ4bXNfdGNkdCI6MTM4MTUwOTQxMH0.YZWoNxLyl8FzBZaX6TECDFrDRs4mhA2Sj97ZS8k9RS6wPlzYzoOWv8oNzt8VW1v61BOoK0YSOc70r5VNHIVLYqKAJ5UtxRpPrcqxPOGtjgjUwH003hMGdmFzQLcf8K-v2WH425S6ycL6bq_FDNyq1qLG8YS3UMZ8WHPCHHLf4eGUtPp_fbUoRNoD6QrxASc60Uuv_F9fxex2WoP3PSp8kwkkQuLbDZY40D4SGNpkj7BBLt2P2DLMsak1gTR4rb1Sab6tif0XS1bHcKEIwaKl80UL19DS4CeKjxv0YXmJbx8mRaQN2Ap8SJmwN-dQRvg-UFHGTg2yGtL1RrHGyvpgGg', 'refresh_token': 'OAQABAAAAAAC5una0EUFgTIF8ElaxtWjT3s_myCPpZ2X69H8ueBV9X4qxbuE78NoeED-spF86M8gMciokNzpf3odlRrIhBDeukA8RvBG2VIciDuKWWwru_H9_1qMFNLMJ2KHT95tBbjOUrpxiSuZLQbecE1FEXc6A5YbxukUaW4TMxKEBb4EPbnolrwv4cp0rC3IdUV3wC11G75Cz6MGUA-jea5zal_zVGJsNqjEzKVi8eayCvzCrxvFpN925ofQkSvCJ5LK3_LuXHrYuxOhkdHbsIgH0GMAEE9T2PIT-JKOE4hukIVhq9z9vnRIC5SV025zKfo6XhYbfe177olJt9z5KfKJ4PKXIwCbMeo-MOCP-EuEUrpgo_QYUGRrGYTUWANvpJf5Jx_uhTmUxRt3QN-L7MUxhHaibqHKWLhwI_rQZBcIB6eABrdu3VOroO_jlRwGabuh7uRwdYeLhT216DG0cjuAhXUUaaFdKOa5o4JtW8RJOEWYAhvntH-tFwP9zh9AsQVGlhUfs6KxJG0iSRTN7LJnwldmRhkyhfuG6TWq65nM7t8ogwg3bMI37xQ4yN1ySwwJUA3vRc1Nyorba2QaNOHRgBXH-zpdNxACEnW4ziP5RBawOc2h1b6O2MBT3i0SCStRWHrRkTkibd29k6LT74cStwPRro5O7ac4XDL9ymtZb3f2vJSb3JCzIME-r3BAZI2mhevdiBuBjzTpwsd_6vnR4vDjZwivIbwPXKWXBMCzsEGBON8XYS3lFzSd62bHceroNuAnBAp1TjfeVUMLvge4vHUEKFG5BfuQbpP8TTXD_rB_MtzQA5tTAAV_twEyjfbxnFK8gAA', 'expires_at': 1545327450.494499} to request.
DEBUG:requests_oauthlib.oauth2_session:Requesting url https://graph.microsoft.com/beta/users/m.roy@mercuryfilmworks.com/calendars/AQMkADNjZjdkZjJhLTljMDYtNDQAMWUtODA0My0yZjkwZDk3ODUxNWYARgAAA-ycYdq22mJNqg2XXXOkdHwHAMH9v4slMY5BjwG8gEnLjocAAAIBBgAAAMH9v4slMY5BjwG8gEnLjocAAAIwUwAAAA==/events using method get.
DEBUG:requests_oauthlib.oauth2_session:Supplying headers {'Prefer': 'outlook.timezone="UTC"', 'Authorization': 'Bearer eyJ0eXAiOiJKV1QiLCJub25jZSI6IkFRQUJBQUFBQUFDNXVuYTBFVUZnVElGOEVsYXh0V2pUdXozeEVqUWlQZ2N2MklmV0NrbDIwOUpjeHNveUhTZzZMckw3TDh4WTNuUnZPVDdsOU10VGFFRXhaLVlkM21sM05tWHhLWnM4aFJ2cF9Pc3FmR0hVU1NBQSIsImFsZyI6IlJTMjU2IiwieDV0IjoibmJDd1cxMXczWGtCLXhVYVh3S1JTTGpNSEdRIiwia2lkIjoibmJDd1cxMXczWGtCLXhVYVh3S1JTTGpNSEdRIn0.eyJhdWQiOiJodHRwczovL2dyYXBoLm1pY3Jvc29mdC5jb20iLCJpc3MiOiJodHRwczovL3N0cy53aW5kb3dzLm5ldC9mOTNlZjA1MC03YjMyLTQzNGMtODcxNi03ZTFhZWIyMzliYzYvIiwiaWF0IjoxNTQ1MzIzNTUwLCJuYmYiOjE1NDUzMjM1NTAsImV4cCI6MTU0NTMyNzQ1MCwiYWNjdCI6MCwiYWNyIjoiMSIsImFpbyI6IjQyUmdZT0NZY0xaTVo2dGhrM0w1QWRkVUZuNnZGYXYvL1A0WXFPbFdjdEcrTHZFV3Z3Y0EiLCJhbXIiOlsicHdkIl0sImFwcF9kaXNwbGF5bmFtZSI6Ik15dGNoVGVzdFB5QXBwR3JhcGgyLjAiLCJhcHBpZCI6ImMwZjc1MTRmLWMyZjgtNDdlOS04YmRjLTcyMjcxOGVjZGNkYiIsImFwcGlkYWNyIjoiMSIsImZhbWlseV9uYW1lIjoiUm95IiwiZ2l2ZW5fbmFtZSI6Ik15dGNoZWxsIiwiaXBhZGRyIjoiMTkyLjQwLjIzMi4yMjYiLCJuYW1lIjoiTXl0Y2hlbGwgUm95Iiwib2lkIjoiNGYwMDBkMTEtMWRiMC00MWE0LWJlMTAtYzQ4YzFmMDEyZjI2Iiwib25wcmVtX3NpZCI6IlMtMS01LTIxLTIzMjU3OTczMDktNzQ0MDUyMDYxLTgxNTY1MDIyNC02OTU0IiwicGxhdGYiOiIzIiwicHVpZCI6IjEwMDM3RkZFQUM4MUFERTEiLCJzY3AiOiJDYWxlbmRhcnMuUmVhZFdyaXRlIENvbnRhY3RzLlJlYWRXcml0ZSBNYWlsLlJlYWRXcml0ZSBNYWlsLlNlbmQgVXNlci5SZWFkIHByb2ZpbGUgb3BlbmlkIGVtYWlsIiwic3ViIjoiLXNYaDA2b21nWWFPSE1fQUtRMk5KcElSc1RCUThpdS1icmp4R3Y3SDI1TSIsInRpZCI6ImY5M2VmMDUwLTdiMzItNDM0Yy04NzE2LTdlMWFlYjIzOWJjNiIsInVuaXF1ZV9uYW1lIjoibS5yb3lAbWVyY3VyeWZpbG13b3Jrcy5jb20iLCJ1cG4iOiJtLnJveUBtZXJjdXJ5ZmlsbXdvcmtzLmNvbSIsInV0aSI6IlZuREhvbUFWTjBLU09NU3hRWWM5QUEiLCJ2ZXIiOiIxLjAiLCJ4bXNfc3QiOnsic3ViIjoiNnMzaE53UXJXaEEzeGpVV1g2dDk0QnlQN3BhYWdYSzFmUWdiV09QWVlXUSJ9LCJ4bXNfdGNkdCI6MTM4MTUwOTQxMH0.YZWoNxLyl8FzBZaX6TECDFrDRs4mhA2Sj97ZS8k9RS6wPlzYzoOWv8oNzt8VW1v61BOoK0YSOc70r5VNHIVLYqKAJ5UtxRpPrcqxPOGtjgjUwH003hMGdmFzQLcf8K-v2WH425S6ycL6bq_FDNyq1qLG8YS3UMZ8WHPCHHLf4eGUtPp_fbUoRNoD6QrxASc60Uuv_F9fxex2WoP3PSp8kwkkQuLbDZY40D4SGNpkj7BBLt2P2DLMsak1gTR4rb1Sab6tif0XS1bHcKEIwaKl80UL19DS4CeKjxv0YXmJbx8mRaQN2Ap8SJmwN-dQRvg-UFHGTg2yGtL1RrHGyvpgGg'} and data None
DEBUG:requests_oauthlib.oauth2_session:Passing through key word arguments {'params': {'$top': 10, '$filter': "start/dateTime ge '2018-08-25T04:00:00+00:00' and end/dateTime lt '2018-12-25T05:00:00+00:00'"}, 'allow_redirects': True}.
DEBUG:urllib3.connectionpool:https://graph.microsoft.com:443 "GET /beta/users/m.roy@mercuryfilmworks.com/calendars/AQMkADNjZjdkZjJhLTljMDYtNDQAMWUtODA0My0yZjkwZDk3ODUxNWYARgAAA-ycYdq22mJNqg2XXXOkdHwHAMH9v4slMY5BjwG8gEnLjocAAAIBBgAAAMH9v4slMY5BjwG8gEnLjocAAAIwUwAAAA==/events?%24top=10&%24filter=start%2FdateTime+ge+%272018-08-25T04%3A00%3A00%2B00%3A00%27+and+end%2FdateTime+lt+%272018-12-25T05%3A00%3A00%2B00%3A00%27 HTTP/1.1" 200 None
INFO:O365.connection:Received response (200) from URL https://graph.microsoft.com/beta/users/m.roy@mercuryfilmworks.com/calendars/AQMkADNjZjdkZjJhLTljMDYtNDQAMWUtODA0My0yZjkwZDk3ODUxNWYARgAAA-ycYdq22mJNqg2XXXOkdHwHAMH9v4slMY5BjwG8gEnLjocAAAIBBgAAAMH9v4slMY5BjwG8gEnLjocAAAIwUwAAAA==/events?%24top=10&%24filter=start%2FdateTime+ge+%272018-08-25T04%3A00%3A00%2B00%3A00%27+and+end%2FdateTime+lt+%272018-12-25T05%3A00%3A00%2B00%3A00%27
date value out of range
Traceback (most recent call last):
  File "QTOverviewer_GUI_100.py", line 158, in loadLists
    jobDateCalList = m.calEventPullJobs()
  File "C:\Users\mytchellr\Desktop\python_o365_test\Overviewer_Beta\1.0.0\QTOverviewer_Main_100.py", line 349, in calEventPullJobs
    for event in events: #iterate events
UnboundLocalError: local variable 'events' referenced before assignment
```

I have changed my calendar statement to fetch the default calendar. Both yield same results.

```
#my_calendar = my_schedule.get_calendar("Calendar")
my_calendar = my_schedule.get_default_calendar()
```

Full code is below if you want.
```
def calEventPullJobs():
	global my_connection
	global my_account
	global jobEventList
			
	try: #load sched
		my_schedule = my_account.schedule()
		print("Loaded: Schedule - Success.")
	except Exception as e:
		print (str(e))

	try: #load cal
		#my_calendar = my_schedule.get_calendar("Calendar")
		my_calendar = my_schedule.get_default_calendar()
		print("Loaded: Calendar - Success.")
	except Exception as e:
		print (str(e))
	
	try: #make query
		q = my_calendar.new_query('start').greater_equal(dt.datetime(2018, 8, 25))
		q.chain('and').on_attribute('end').less(dt.datetime(2018, 12, 25))
		print("Loaded: Calendar Query - Success.")
	except Exception as e:
		print (str(e))
			
	try: #load events
		print ("DEBUG-queryVar: {}".format(q))
		events = my_calendar.get_events(limit=10, query=q)
		print("Loaded: Events - Success.")
	except Exception as e:
		print (str(e))		
		
	for event in events: #iterate events
		print (event)	
		if event is None:
			print ("WARNING: There is a blank event in the Outlook calendar")
		else:
			jobEventList.append(event)
	return jobEventList

```

**Comment by MintyFresh0** [comment] 2018-12-20 19:13
Here is a better direct python output, without the try/except. 

```
Traceback (most recent call last):
  File "C:\Users\mytchellr\Desktop\python_o365_test\Overviewer_Beta\1.0.0\QTOverviewer_Main_100.py", line 525, in <module>
    calEventPullJobs()
  File "C:\abcdefg\1.0.0\QTOverviewer_Main_100.py", line 371, in calEventPullJobs
    events = my_calendar.get_events(limit=10, query=q)
  File "C:/msys64/mingw64/lib/python3.7/site-packages\O365\calendar.py", line 1104, in get_events
    for event in data.get('value', [])]
  File "C:/msys64/mingw64/lib/python3.7/site-packages\O365\calendar.py", line 1104, in <listcomp>
    for event in data.get('value', [])]
  File "C:/msys64/mingw64/lib/python3.7/site-packages\O365\calendar.py", line 574, in __init__
    self.__attendees = Attendees(event=self, attendees={self._cloud_data_key: cloud_data.get(cc('attendees'), [])})
  File "C:/msys64/mingw64/lib/python3.7/site-packages\O365\calendar.py", line 447, in __init__
    self.add(attendees)
  File "C:/msys64/mingw64/lib/python3.7/site-packages\O365\calendar.py", line 506, in add
    response_status=attendee.get(self._cc('status'), {}))))
  File "C:/msys64/mingw64/lib/python3.7/site-packages\O365\calendar.py", line 363, in __init__
    self.response_time = parse(self.response_time).astimezone(self.protocol.timezone)
  File "C:/msys64/mingw64/lib/python3.7/site-packages\pytz\tzinfo.py", line 201, in fromutc
    return (dt + inf[0]).replace(tzinfo=self._tzinfos[inf])
OverflowError: date value out of range
```

**Comment by MintyFresh0** [comment] 2018-12-20 21:50
1. I'm not entirely sure what you mean, where would I find this time?

2. timezone prints as "America/New_York", which is correct, or at least the same time for my location (Ontario, Canada)

3. MS Graph Protocol (api_version='beta')


This is the function that I run on startup:
```
def loginInitAccount():
	my_credentials = ('removed', 'removed')
	my_protocol = MSGraphProtocol(api_version='beta')
	print (my_protocol.timezone)
	my_scopes_graph = ['https://graph.microsoft.com/Mail.ReadWrite', 'https://graph.microsoft.com/Mail.Send', 'https://graph.microsoft.com/Calendars.ReadWrite', 'https://graph.microsoft.com/Contacts.ReadWrite', 'offline_access']
	my_connection = Connection(credentials = my_credentials, scopes=my_scopes_graph)
	my_account = Account(credentials=my_credentials, main_resource="m.roy@mercuryfilmworks.com", protocol=my_protocol)
	my_connection.refresh_token

```

**Comment by janscas** [comment] 2018-12-20 21:59
> This is the function that I run on startup:

A few things on this.

The initialisation is correct but note that once you have retrieved the token (the token file is stored) then you don't need to create a connection nor call refresh_token on it. In fact, token refreshment is done automatically for you as long as you got it with the 'offline_access' scope.

So following your example, this is enough:

```python
def loginInitAccount():
	my_credentials = ('removed', 'removed')
	my_protocol = MSGraphProtocol(api_version='beta')
	my_account = Account(credentials=my_credentials, main_resource="m.roy@mercuryfilmworks.com", protocol=my_protocol)
```
Although note that you must use the same protocol that you used when requesting the token (not api version):

**Comment by janscas** [comment] 2018-12-20 22:06
> 1. I'm not entirely sure what you mean, where would I find this time?

I can't reproduce the error you are getting. The request does not fail (it returned 200 ok), so it is correct, but for some reason the program is unable to parse the response.

An attendee response status time is what fails.

Maybe you can inject a temporary "print" into the O365 Library on calendar.py after line 361:

calendar.py: L361: `self.response_time = response_status.get(self._cc('time'), None)`

so just inject this after:
`print(self.response_time)`

with the same example the last print should show the value that is failing.

I know it's not pretty but it will be fast.

Thanks

**Comment by MintyFresh0** [comment] 2019-01-02 19:45
Hey Janscas, sorry to be out for a week. This is a work related issue and I was on holidays as of the 21st.

Here are the modifications to calendar.py:
```
        if self.status:
            self.response_time = response_status.get(self._cc('time'), None)
            print("MINTYFRESH RESPONSE TIME: {}".format(self.response_time))
            print("MINTYFRESH TIMEZONE: {}".format(self.protocol.timezone))

            if self.response_time:
                self.response_time = parse(self.response_time).astimezone(self.protocol.timezone)
        else:
            self.response_time = None
```
And here is the new output:
```
DEBUG:requests_oauthlib.oauth2_session:Passing through key word arguments {'params': {'$top': 10, '$filter': "start/dateTime ge '2018-08-25T04:00:00+00:00' and end/dateTime lt '2018-12-25T05:00:00+00:00'"}, 'allow_redirects': True}.
DEBUG:urllib3.connectionpool:https://graph.microsoft.com:443 "GET /beta/users/m.roy@mercuryfilmworks.com/calendars/AQMkADNjZjdkZjJhLTljMDYtNDQAMWUtODA0My0yZjkwZDk3ODUxNWYARgAAA-ycYdq22mJNqg2XXXOkdHwHAMH9v4slMY5BjwG8gEnLjocAAAIBBgAAAMH9v4slMY5BjwG8gEnLjocAAAIwUwAAAA==/events?%24top=10&%24filter=start%2FdateTime+ge+%272018-08-25T04%3A00%3A00%2B00%3A00%27+and+end%2FdateTime+lt+%272018-12-25T05%3A00%3A00%2B00%3A00%27 HTTP/1.1" 200 None
INFO:O365.connection:Received response (200) from URL https://graph.microsoft.com/beta/users/m.roy@mercuryfilmworks.com/calendars/AQMkADNjZjdkZjJhLTljMDYtNDQAMWUtODA0My0yZjkwZDk3ODUxNWYARgAAA-ycYdq22mJNqg2XXXOkdHwHAMH9v4slMY5BjwG8gEnLjocAAAIBBgAAAMH9v4slMY5BjwG8gEnLjocAAAIwUwAAAA==/events?%24top=10&%24filter=start%2FdateTime+ge+%272018-08-25T04%3A00%3A00%2B00%3A00%27+and+end%2FdateTime+lt+%272018-12-25T05%3A00%3A00%2B00%3A00%27
MINTYFRESH RESPONSE TIME: 0001-01-01T00:00:00Z
MINTYFRESH TIMEZONE: America/New_York
Traceback (most recent call last):
  File "QTOverviewer_GUI_100.py", line 7, in <module>
    import QTOverviewer_Main_100
  File "C:\Users\mytchellr\Desktop\python_o365_test\Overviewer_Beta\1.0.0\QTOverviewer_Main_100.py", line 533, in <module>
    calEventPullJobs()
  File "C:\Users\mytchellr\Desktop\python_o365_test\Overviewer_Beta\1.0.0\QTOverviewer_Main_100.py", line 375, in calEventPullJobs
    events = my_calendar.get_events(limit=10, query=q)
  File "C:/msys64/mingw64/lib/python3.7/site-packages\O365\calendar.py", line 1106, in get_events
    for event in data.get('value', [])]
  File "C:/msys64/mingw64/lib/python3.7/site-packages\O365\calendar.py", line 1106, in <listcomp>
    for event in data.get('value', [])]
  File "C:/msys64/mingw64/lib/python3.7/site-packages\O365\calendar.py", line 576, in __init__
    self.__attendees = Attendees(event=self, attendees={self._cloud_data_key: cloud_data.get(cc('attendees'), [])})
  File "C:/msys64/mingw64/lib/python3.7/site-packages\O365\calendar.py", line 449, in __init__
    self.add(attendees)
  File "C:/msys64/mingw64/lib/python3.7/site-packages\O365\calendar.py", line 508, in add
    response_status=attendee.get(self._cc('status'), {}))))
  File "C:/msys64/mingw64/lib/python3.7/site-packages\O365\calendar.py", line 365, in __init__
    self.response_time = parse(self.response_time).astimezone(self.protocol.timezone)
  File "C:/msys64/mingw64/lib/python3.7/site-packages\pytz\tzinfo.py", line 201, in fromutc
    return (dt + inf[0]).replace(tzinfo=self._tzinfos[inf])
OverflowError: date value out of range
```


Since the response time is "0001-01-01T00:00:00Z", I would the assume the issue might be related to parsing the response time out of the response. 
This was executed at 2:34 PM on Jan. 2nd.

**Comment by janscas** [comment] 2019-01-03 10:58
I have just committed a fix.
It will be available on pypi on the next release.

**Closed** 2019-01-03 10:57 UTC

**Comment by janscas** [comment] 2019-01-03 16:39
@Narcolapser, @roycem90, It’s a temporary fix. Just catching the exception and returning None. I don’t know how to ñarse this date.

**Comment by MintyFresh0** [comment] 2019-01-03 20:34
Thanks Alejandro, looking forward to playing around with the next release!
Appreciate the extended support on this issue.

How should I best circumvent this while waiting for the release? I'm just gonna wrap the parsing line in a try except for now.

**Comment by janscas** [comment] 2019-01-03 20:35
Install from github using pip

**Comment by MintyFresh0** [comment] 2019-01-04 19:36
Thank you. Let me know if any of the three of you (@janscas @Narcolapser @roycem90 ) ever open this issue back up, I'd be happy to help replicate the issue or give more details.
